// Starter theme (Tailwind v4-style token set).
import type { Token } from '../../model/types'

export const STARTER_THEME: Token[] = [
  { name: '--color-gray-50', value: 'oklch(98.5% 0 0)' },
  { name: '--color-gray-100', value: 'oklch(97% 0 0)' },
  { name: '--color-gray-200', value: 'oklch(92.2% 0 0)' },
  { name: '--color-gray-300', value: 'oklch(87% 0 0)' },
  { name: '--color-gray-400', value: 'oklch(70.8% 0 0)' },
  { name: '--color-gray-500', value: 'oklch(55.6% 0 0)' },
  { name: '--color-gray-600', value: 'oklch(43.9% 0 0)' },
  { name: '--color-gray-700', value: 'oklch(37.1% 0 0)' },
  { name: '--color-gray-800', value: 'oklch(26.9% 0 0)' },
  { name: '--color-gray-900', value: 'oklch(20.5% 0 0)' },
  { name: '--color-gray-950', value: 'oklch(14.5% 0 0)' },
  { name: '--color-blue-50', value: 'oklch(97% 0.014 258)' },
  { name: '--color-blue-100', value: 'oklch(93.2% 0.032 258)' },
  { name: '--color-blue-200', value: 'oklch(88.2% 0.059 258)' },
  { name: '--color-blue-300', value: 'oklch(80.9% 0.105 258)' },
  { name: '--color-blue-400', value: 'oklch(70.7% 0.165 258)' },
  { name: '--color-blue-500', value: 'oklch(62.3% 0.214 258)' },
  { name: '--color-blue-600', value: 'oklch(54.6% 0.220 258)' },
  { name: '--color-blue-700', value: 'oklch(49% 0.200 258)' },
  { name: '--color-blue-800', value: 'oklch(44% 0.162 258)' },
  { name: '--color-blue-900', value: 'oklch(37.9% 0.146 258)' },
  { name: '--color-blue-950', value: 'oklch(28.2% 0.091 258)' },
  { name: '--font-sans', value: 'Inter' },
  { name: '--font-serif', value: 'Georgia' },
  { name: '--font-mono', value: 'DM Mono' },
  { name: '--text-xs', value: '12px' },
  { name: '--text-sm', value: '14px' },
  { name: '--text-base', value: '16px' },
  { name: '--text-lg', value: '18px' },
  { name: '--text-xl', value: '20px' },
  { name: '--text-2xl', value: '24px' },
  { name: '--text-3xl', value: '30px' },
  { name: '--text-4xl', value: '36px' },
  { name: '--text-5xl', value: '48px' },
  { name: '--text-6xl', value: '60px' },
  { name: '--text-7xl', value: '72px' },
  { name: '--text-8xl', value: '96px' },
  { name: '--text-9xl', value: '128px' },
  { name: '--font-weight-thin', value: '100' },
  { name: '--font-weight-extralight', value: '200' },
  { name: '--font-weight-light', value: '300' },
  { name: '--font-weight-normal', value: '400' },
  { name: '--font-weight-medium', value: '500' },
  { name: '--font-weight-semibold', value: '600' },
  { name: '--font-weight-bold', value: '700' },
  { name: '--font-weight-extrabold', value: '800' },
  { name: '--font-weight-black', value: '900' },
  { name: '--tracking-tighter', value: '-0.05em' },
  { name: '--tracking-tight', value: '-0.025em' },
  { name: '--tracking-normal', value: '0em' },
  { name: '--tracking-wide', value: '0.025em' },
  { name: '--tracking-wider', value: '0.05em' },
  { name: '--tracking-widest', value: '0.1em' },
  { name: '--leading-tight', value: '125%' },
  { name: '--leading-snug', value: '137.5%' },
  { name: '--leading-normal', value: '150%' },
  { name: '--leading-relaxed', value: '162.5%' },
  { name: '--leading-loose', value: '200%' },
  { name: '--breakpoint-sm', value: '640px' },
  { name: '--breakpoint-md', value: '768px' },
  { name: '--breakpoint-lg', value: '1024px' },
  { name: '--breakpoint-xl', value: '1280px' },
  { name: '--breakpoint-2xl', value: '1536px' },
  { name: '--container-3xs', value: '256px' },
  { name: '--container-2xs', value: '288px' },
  { name: '--container-xs', value: '320px' },
  { name: '--container-sm', value: '384px' },
  { name: '--container-md', value: '448px' },
  { name: '--container-lg', value: '512px' },
  { name: '--container-xl', value: '576px' },
  { name: '--container-2xl', value: '672px' },
  { name: '--container-3xl', value: '768px' },
  { name: '--container-4xl', value: '896px' },
  { name: '--container-5xl', value: '1024px' },
  { name: '--container-6xl', value: '1152px' },
  { name: '--container-7xl', value: '1280px' },
  { name: '--radius-xs', value: '2px' },
  { name: '--radius-sm', value: '4px' },
  { name: '--radius-md', value: '6px' },
  { name: '--radius-lg', value: '8px' },
  { name: '--radius-xl', value: '12px' },
  { name: '--radius-2xl', value: '16px' },
  { name: '--radius-3xl', value: '24px' },
  { name: '--radius-4xl', value: '32px' },
]
